get:
  tags:
    - project
  summary: プロジェクト一覧
  description: プロジェクトの一覧を取得します
  operationId: projectIndex
  parameters:
    - $ref: '#/components/parameters/ACCEPT'
    - $ref: '#/components/parameters/CONTENT-TYPE'
    - $ref: '#/components/parameters/NONCE'
    - $ref: '#/components/parameters/TOKEN'
    - $ref: '#/components/parameters/PER'
    - $ref: '#/components/parameters/PAGE'
    - $ref: '#/components/parameters/ORDER'
    - $ref: '#/components/parameters/KEYWORD'
  security:
    - cookieAuth: []
  responses:
    200:
      description: プロジェクトの一覧
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                $ref: '#/components/schemas/StatusResource'
              payloads:
                type: object
                properties:
                  meta:
                    $ref: '#/components/schemas/MetaResource'
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/ProjectResource'
post:
  tags:
    - project
  summary: プロジェクト登録
  description: プロジェクトを登録します
  operationId: projectStore
  parameters:
    - $ref: '#/components/parameters/ACCEPT'
    - $ref: '#/components/parameters/CONTENT-TYPE'
    - $ref: '#/components/parameters/NONCE'
    - $ref: '#/components/parameters/TOKEN'
  security:
    - cookieAuth: []
  requestBody:
    content:
      application/json:
        schema:
          $ref: '#/components/schemas/ProjectResource'
  responses:
    201:
      description: プロジェクト登録
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ProjectResource'
