name: versioning

on:
  push:
    branches:
      - main
    paths:
      - version.json
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          ref: main

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: set version
        run: node -p -e 'const version=require("./version.json");`RELEASED_VERSION=v${version[version.length - 1]["version"]}`' >> $GITHUB_ENV

      - name: create release branch
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git branch release-${{ env.RELEASED_VERSION }}
          git push -u origin release-${{ env.RELEASED_VERSION }}
          git branch -a

      - name: create release
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d "{ \"tag_name\": \"${{ env.RELEASED_VERSION }}\", \"name\": \"${{ env.RELEASED_VERSION }}\", \"generate_release_notes\": true }" \
            https://api.github.com/repos/${GITHUB_REPOSITORY}/releases
